import streamlit as st
from datetime import date
import re

PROFILE_IMAGE="https://lh3.googleusercontent.com/N1e2uaHFARa5DtP9MUr2DVqqe8EF4sKsA1H_Gqz8TPixg_6UgPFx0-r1RQDGn1-W-BP4m7mEv2IH8VgPohX_6W0v91qzDx7NpoYBfQHbE-9u5cXFPwJKtilHfTL2Mm-Yr_GuAiP5wuIT_HVOP8XqJA.png"


BACKGROUND_IMAGE="https://lh4.googleusercontent.com/FuVHZA6Mrp7tcnxdfyJdz2Xa6t-RmwJuJTHsZYzJVej_i0FtO1Y91nDFpnM5Vezj_sB1fsV3ygGiSgPhVOnZ1x5nEdlEHuJwR9RPO9JjdT99j24jCbXsKz6ytaE6h7ONA7CfDmHAesaGoUhaFw1qwg.png"

PAGE_TITLE="SH1: Investigating Deepfakes from Real Images"

FOOTER_TEXT=f"by Heva - {date.today().year}"

st.set_page_config(
    page_title=PAGE_TITLE,
    page_icon="🧊",
    layout="wide",
    initial_sidebar_state="expanded",
)

def get_page_title_id():
  s = re.sub(r"[^\w\s]", '', PAGE_TITLE)
  s = re.sub(r'\[\[(?:[^\]|]*\|)?([^\]|]*)\]\]', r'\1', s)
  s = re.sub(r"\s+", '-', s)
  return s.lower()

HEADER_STYLE=f"""<style>
	    [data-testid="stToolbar"]{{
	    visibility: hidden;
	    top: -50px;
	    }}
            #root > div:nth-child(1) > div > div > div > div > section > div > div:nth-child(1) > div > div:nth-child(1) > div > div > div > div:nth-child(1) > div > div > div > div > div{{
            height: 300px;
            width: 300px;
            }}
            #root > div:nth-child(1) > div > div > div > div > section > div > div:nth-child(1) > div > div:nth-child(1) > div > div > div > div:nth-child(1) > div > div > div > div > div > img{{
            height: 300px;
            width: 300px;
            padding-top: 40%;
            padding-bottom: 10%;
            padding-left: 15%;
            padding-right: 10%;
            }}
            #root > div:nth-child(1) > div > div > div > div > section > div > div:nth-child(1) > div > div:nth-child(1) > div{{
            background-image: url("{BACKGROUND_IMAGE}");
            background-size: cover; 
            background-position: center;
            }}
            #{get_page_title_id()}{{
            height: 250px;
            }}
            #{get_page_title_id()} > div {{
            bottom: 1%;
            position: absolute;
            color: white;
            }}
	    footer {{
            visibility: hidden;
            position: relative;
            }}
            footer:before {{
            visibility: visible;
            position: relative;
	    content: {FOOTER_TEXT}
            }}
	    button[data-baseweb="tab"] > div[data-testid="stMarkdownContainer"] > p {{
            font-size: 24px;
            padding: 0px 20px;
            background-color: rgb(240, 242, 246);
            }}
        </style>
    """

HOMEPAGE_CONTENT='''
#####  Introducing SH1: Unveiling the Truth behind AI-Generated Images

In today's digital age, the ability to distinguish between real and fake images has become increasingly challenging. Inspired by the iconic detective Sherlock Holmes, a new AI-powered product called SH1 has emerged to tackle this issue. SH1 aims to investigate and uncover signs of image tampering using the power of artificial intelligence.

Deepfake technology, driven by advanced AI techniques known as GANs (Generative Adversarial Networks), has made it possible to create highly realistic fake images. These manipulated images can be used to spread misinformation, deceive individuals, or even harm someone's reputation. SH1 is specifically designed to address the challenge of deepfake images generated by popular GANs such as StyleGAN, StyleGAN2, AttGAN, GDWCT, and StarGAN.

With an accuracy rate of 81%, SH1 is effective at detecting deepfake facial images generated by these specific GAN models. By focusing on facial deepfake detection, SH1 provides users with an added layer of protection against identity misuse. However, it's important to note that SH1 is still in the early stages of development and currently has limitations. It may struggle to accurately classify non-facial images or those generated by different GAN models. Nevertheless, the development team behind SH1 is actively working to improve its capabilities and expand its detection capabilities in future versions.

SH1 holds great promise as a tool in the ongoing battle against AI-generated image manipulation. With its AI-powered investigation inspired by Sherlock Holmes, SH1 empowers users to identify and expose deepfake images, specifically those targeting individuals' faces. As SH1 continues to evolve, we can anticipate more advanced versions that will provide users with even better results, ensuring a safer and more trustworthy digital landscape for all.
'''

with st.container():
    col1, col2 = st.columns([1,2], gap="small")
    with col1:
        st.image(PROFILE_IMAGE, width=300)
    with col2:
        st.markdown(HEADER_STYLE, unsafe_allow_html=True)
        st.title(PAGE_TITLE)
st.markdown("<br>", unsafe_allow_html=True)
with st.container():
    project_tab, team_tab, data_source = st.tabs(["  **About Project** "])
    project_tab.markdown("<br>", unsafe_allow_html=True)
    project_tab.markdown(HOMEPAGE_CONTENT, unsafe_allow_html=True)
